### ISSUE TITLE
Implement AIP18

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystemArchive/cpp-crypto#91]
https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-18.md

See https://github.com/ArkEcosystem/core/tree/master/packages/crypto/src for reference once Core 2.6 is released.

**Comment by ciband** [comment]
I would like to see if I can tackle this.

**Comment by ciband** [comment]
I don't think I am going to be able to finish this.  I got started and hit a wall, and do not have the time to put into it.

If anyone wants to see how far i got and where I left off, here is my branch:

https://github.com/ciband/cpp-crypto/tree/feat/aip18

**Comment by sleepdefic1t** [comment]
All good, thank you for giving it a shot, @ciband

**Comment by sleepdefic1t** [comment]
Update: This is working using the newer-ish `libtorsion` for all platforms, just needs some final testing before I open a PR.

**Comment by sleepdefic1t** [comment]
Update 2: 

Using [`libtorsion`](https://github.com/bcoin-org/libtorsion) for crypto operations (_keys, hashing, b58, ecdsa/schnorr-sign/verify_).

| platform | progress | comments |
| :-------: | :--------: | :---------- |
| **Linux** | ✅ | all tests passing |
| **macOS** | ✅ | all tests passing |
| **Windows** | ✅ | all tests passing |
| **[PIO] ESP32** | ~75% | crashes, needs debugging |
| **[Arduino] ESP32** | ~25% | builds, _untested_, needs additional packaging considerations |

**Comment by sleepdefic1t** [comment]
Yeah, so `libtorsion` uses a _massive_ amount of static allocation which does _**not**_ play nice on tiny platforms.

Desktop builds worked just fine.

I previously made some progress using the [secp256k1](https://github.com/bitcoin-core/secp256k1) lib; however, some additional code was required as ARK’s schnorr is a legacy version incompatible with the one currently used by `secp256k1`.

This is in addition to the concerns regarding IoT platforms (`secp256k1` would need custom packaging and configuration to support embedded platforms).
